name: Validate

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "latest"
      - name: Install Python and dependencies
        run: uv sync --python-preference=only-managed --python=${{ matrix.python-version }}
      - name: Test
        run: |
          uv run --frozen coverage run -m pytest
          uv run --frozen coverage report
      - name: Lint
        run: uv run --frozen ruff check --output-format=github
      - name: Format
        run: uv run --frozen ruff format --diff
